"""CloudFormation Specialist agent for generating AWS infrastructure code."""

CLOUDFORMATION_SYSTEM_PROMPT = """You are an AWS CloudFormation expert. Convert architecture diagrams into CloudFormation YAML templates.

## Best Practices

- Use AWS::Serverless transforms for Lambda/API Gateway
- Include Outputs for important resources
- Use !Ref and !GetAtt for resource references
- Add descriptions to all resources
- Use Parameters for configurable values

## Service Templates

### Lambda Function
```yaml
MyFunction:
  Type: AWS::Serverless::Function
  Properties:
    Runtime: nodejs20.x
    Handler: index.handler
    CodeUri: ./src
    Environment:
      Variables:
        TABLE_NAME: !Ref MyTable
    Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref MyTable
```

### DynamoDB Table
```yaml
MyTable:
  Type: AWS::DynamoDB::Table
  Properties:
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
```

### API Gateway
```yaml
MyApi:
  Type: AWS::Serverless::Api
  Properties:
    StageName: prod
    Auth:
      DefaultAuthorizer: MyCognitoAuthorizer
      Authorizers:
        MyCognitoAuthorizer:
          UserPoolArn: !GetAtt UserPool.Arn
```

Respond with valid CloudFormation YAML only."""


class CloudFormationSpecialistAgent:
    """Agent that generates CloudFormation templates."""

    def __init__(self):
        """Initialize the CloudFormation specialist."""
        pass

    async def generate(self, graph: dict) -> str:
        """Generate CloudFormation template from graph."""
        nodes = graph.get("nodes", [])
        edges = graph.get("edges", [])

        template = {
            "AWSTemplateFormatVersion": "2010-09-09",
            "Transform": "AWS::Serverless-2016-10-31",
            "Description": "Generated by Scaffold AI",
            "Resources": {},
            "Outputs": {},
        }

        # Generate resources
        for node in nodes:
            node_type = node.get("type")
            node_id = node.get("id", "").replace("-", "")
            label = node.get("data", {}).get("label", node_type)

            if node_type == "lambda":
                template["Resources"][f"{node_id}Function"] = {
                    "Type": "AWS::Serverless::Function",
                    "Properties": {
                        "Runtime": "nodejs20.x",
                        "Handler": "index.handler",
                        "CodeUri": "./src",
                        "Description": label,
                        "Tracing": "Active",
                    },
                }

            elif node_type == "dynamodb":
                template["Resources"][f"{node_id}Table"] = {
                    "Type": "AWS::DynamoDB::Table",
                    "Properties": {
                        "BillingMode": "PAY_PER_REQUEST",
                        "AttributeDefinitions": [
                            {"AttributeName": "id", "AttributeType": "S"}
                        ],
                        "KeySchema": [{"AttributeName": "id", "KeyType": "HASH"}],
                        "PointInTimeRecoverySpecification": {
                            "PointInTimeRecoveryEnabled": True
                        },
                    },
                }

            elif node_type == "apigateway":
                template["Resources"][f"{node_id}Api"] = {
                    "Type": "AWS::Serverless::Api",
                    "Properties": {"StageName": "prod", "Description": label},
                }

            elif node_type == "cognito":
                template["Resources"][f"{node_id}UserPool"] = {
                    "Type": "AWS::Cognito::UserPool",
                    "Properties": {
                        "UserPoolName": label,
                        "MfaConfiguration": "OPTIONAL",
                    },
                }

            elif node_type == "s3":
                template["Resources"][f"{node_id}Bucket"] = {
                    "Type": "AWS::S3::Bucket",
                    "Properties": {
                        "BucketEncryption": {
                            "ServerSideEncryptionConfiguration": [
                                {"ServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}
                            ]
                        }
                    },
                }

            elif node_type == "sqs":
                template["Resources"][f"{node_id}Queue"] = {
                    "Type": "AWS::SQS::Queue",
                    "Properties": {"QueueName": label},
                }

        # Add outputs
        for resource_name in template["Resources"].keys():
            template["Outputs"][f"{resource_name}Arn"] = {
                "Value": {"Fn::GetAtt": [resource_name, "Arn"]},
                "Description": f"ARN of {resource_name}",
            }

        import yaml

        return yaml.dump(template, default_flow_style=False, sort_keys=False)
